default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: ember_api_development

test:
  <<: *default
  database: ember_api_test

production:
  <<: *default
  database: ember_api_production
  username: ember_api
  password: <%= ENV['EMBER_API_DATABASE_PASSWORD'] %>
